packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
pnpFallbackMode: all
yarnPath: .yarn/releases/yarn-3.2.0.cjs
